type NFTMembershipCreated @entity {
  id: ID!
  contractAddress: Bytes!
  memberTypeNames: [String!]!
  defaultImageURL: String!
  POname: String!
}

type NFTMembership @entity {
  id: ID!
  contract: NFTMembershipCreated! @link
  memberTypeNames: [String!]!
  defaultImageURL: String!
  mintEvents: [NFTMintEvent!]! @derivedFrom(field: "membership")
  changeTypeEvents: [NFTChangeTypeEvent!]! @derivedFrom(field: "membership")
}

type NFTMemberType @entity {
  id: ID!
  memberTypeName: String!
  imageURL: String!
  membership: NFTMembership! @link
}

type NFTMintEvent @entity {
  id: ID!
  membership: NFTMembership! @link
  recipient: Bytes!
  memberTypeName: String!
  tokenURI: String!
}

type NFTChangeTypeEvent @entity {
  id: ID!
  membership: NFTMembership! @link
  user: Bytes!
  newMemberType: String!
}
